version: "3.7"
services:
  mariadb:
    hostname: mariadb
    image: linuxserver/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - network
    restart: unless-stopped
    volumes:
      - ${DATABASE_DIR}:/config

  api:
    hostname: api
    image: vikunja/api:latest
    environment:
      TZ: ${TZ}
      VIKUNJA_DATABASE_HOST: 'mariadb'
      VIKUNJA_DATABASE_USER: ${DATABASE_USER}
      VIKUNJA_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      VIKUNJA_DATABASE_DATABASE: ${DATABASE_NAME}
      VIKUNJA_DATABASE_TYPE: mysql
    networks:
      - network
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/files:/app/vikunja/files
    depends_on:
      - mariadb

  frontend:
    hostname: frontend
    image: vikunja/frontend:latest
    networks:
      - network
    restart: unless-stopped
    depends_on:
      - api

  proxy:
    hostname: proxy
    image: nginx
    ports:
      - 3456:80
    volumes:
      - ${CONFIG_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - network
    restart: unless-stopped
    depends_on:
      - api
      - frontend

networks:
  network:
